version: 2.1
 
orbs:
    android: circleci/android@0.2.1
    browser-tools: circleci/browser-tools@1.2.3

jobs:
    build:
        docker:
            - image: cimg/openjdk:17.0-browsers
              auth:
                username: mydockerhub-user
                password: $DOCKERHUB_PASSWORD 
        executor: android/android
        steps:
            - checkout
            - browser-tools/install-browser-tools
            - restore_cache:
                key: android-orb-v1-
            - run:
                name: Chmod permissions
                command: sudo chmod +x ./gradlew
            - run:
                name: Download Dependencies
                command: ./gradlew androidDependencies
            - save_cache:
                key: 'android-orb-v1-{{ epoch }}'
                paths:
                    - ~/.android/build-cache
                    - ~/.android/cache
            - run:
                name: Run Build
                command: ./gradlew build
            - store_artifacts: 
                path: app/build/reports
                destination: reports
            - run:
                name: Run Tests
                command: ./gradlew lint test
            - run : mvn test
            - store_test_results:
                path: app/build/test-results
            - store_artifacts:  
                path: app/build/outputs/apk/debug/
                destination: artifact-file